"""add analysis_run, recommendation, agent_opinion tables

Revision ID: ba8af20c4e1a
Revises: 2a431fa71f94
Create Date: 2026-09-26 22:05:20.128989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba8af20c4e1a'
down_revision: Union[str, None] = '2a431fa71f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING', 'COMPLETED', 'FAILED')", name='ck_analysis_run_status'),
    sa.CheckConstraint("triggered_by IN ('MANUAL', 'SCHEDULED', 'API')", name='ck_analysis_run_triggered_by'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_opinion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reasoning_text', sa.Text(), nullable=False),
    sa.Column('raw_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("agent_name IN ('SENTIMENT', 'QUANT', 'FUNDAMENTAL')", name='ck_agent_opinion_agent_name'),
    sa.CheckConstraint("verdict IN ('BUY', 'HOLD', 'SELL')", name='ck_agent_opinion_verdict'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('final_verdict', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("final_verdict IN ('BUY', 'HOLD', 'SELL')", name='ck_recommendation_final_verdict'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('agent_opinion')
    op.drop_table('analysis_run')
    # ### end Alembic commands ###
